steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/malabro-backend:latest',
      '-t', 'gcr.io/$PROJECT_ID/malabro-backend:$BUILD_ID',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/malabro-backend:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/malabro-backend:$BUILD_ID']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'malabro-backend',
      '--image', 'gcr.io/$PROJECT_ID/malabro-backend:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8000',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--set-env-vars', 'DATABASE_URL=${_DATABASE_URL},SUPABASE_URL=${_SUPABASE_URL},SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY},SUPABASE_SERVICE_ROLE_KEY=${_SUPABASE_SERVICE_ROLE_KEY},JWT_SECRET_KEY=${_JWT_SECRET_KEY},SMTP_SERVER=${_SMTP_SERVER},SMTP_PORT=${_SMTP_PORT},SMTP_USERNAME=${_SMTP_USERNAME},SMTP_PASSWORD=${_SMTP_PASSWORD},ADMIN_EMAIL=${_ADMIN_EMAIL}'
    ]

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/malabro-backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/malabro-backend:latest'

# Substitution variables (to be set in Cloud Build trigger)
substitutions:
  _DATABASE_URL: 'postgresql://postgres.zfczihnyifgoinhodsfd:malabro_shop@aws-0-us-west-1.pooler.supabase.com:6543/postgres'
  _SUPABASE_URL: 'https://zfczihnyifgoinhodsfd.supabase.co'
  _SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmY3ppaG55aWZnb2luaG9kc2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjc0NDIsImV4cCI6MjA2NzkwMzQ0Mn0.W9vq9SPslpfj1amhMibRUWolXveB5oCGgOLPxubF6Jo'
  _SUPABASE_SERVICE_ROLE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmY3ppaG55aWZnb2luaG9kc2ZkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MjMyNzQ0MiwiZXhwIjoyMDY3OTAzNDQyfQ.service-role-key-placeholder'
  _JWT_SECRET_KEY: 'malabro-super-secret-jwt-key-2024'
  _SMTP_SERVER: 'smtp.gmail.com'
  _SMTP_PORT: '587'
  _SMTP_USERNAME: 'yayakof45@gmail.com'
  _SMTP_PASSWORD: 'your-gmail-app-password'
  _ADMIN_EMAIL: 'admin@malabro.com'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
